# Generated by Django 5.2.8 on 2026-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_total_extra_price_cartitem_extra_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='chocolate_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ExtraBerry',
        ),
        migrations.DeleteModel(
            name='ExtraFlower',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='packaging_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_extra_price',
            new_name='extra_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra_flowers',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='chocolate_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flower_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flower_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra_berries',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ChocolateType',
        ),
        migrations.DeleteModel(
            name='PackagingType',
        ),
    ]
